[package]
name = "crypto"
version = "6.6.4"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.21", features = ["full"] }
hex = "0.4"
tower = "0.4"
tiny-keccak = { version = "2.0", features = ["keccak"] }
secp256k1 = {version = "0.24", features = ["rand", "recovery"]}
lazy_static = "1.4"
rayon = "1.5"
serde = "1.0"
serde_derive = "1.0"
backtrace = "0.3"
tracing = "0.1"

cloud-util = "=0.6.1"
cita_cloud_proto = "=6.6.4"

[dev-dependencies]
rand = "0.8" # must be match deps of secp256k1

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
