[package]
name = "crypto"
version = "6.3.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0", features = ["default", "gzip"] }
clap = { version = "3.0.14", features = ["derive"] }
git-version = "0.3.5"
tonic = "0.5.2"
prost = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
hex = "0.4"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util", branch = "WIP-v7.0.0" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "WIP-v7.0.0" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code", branch = "WIP-v7.0.0" }

tiny-keccak = { version = "2.0.2", features = ["keccak"] }
secp256k1 = {version = "0.20.2", features = ["rand", "recovery"]}
lazy_static = "1.4.0"
rayon = "1.5"
serde = "1.0.126"
serde_derive = "1.0.126"

[dev-dependencies]
rand = "0.6" # must be match deps of secp256k1

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
