[package]
name = "crypto"
version = "6.6.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = { version = "1.0", features = ["gzip"] }
clap = { version = "3.2", features = ["derive"] }
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.20", features = ["full"] }
hex = "0.4"
tower = "0.4.13"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code" }

tiny-keccak = { version = "2.0", features = ["keccak"] }
secp256k1 = {version = "0.24", features = ["rand", "recovery"]}
lazy_static = "1.4"
rayon = "1.5"
serde = "1.0"
serde_derive = "1.0"

backtrace = "0.3"

[dev-dependencies]
rand = "0.8" # must be match deps of secp256k1

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
